import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const URL="https://kqkpbqpfnupjpthtpvdn.supabase.co",KEY="sb_publishable_AVVPm0Pr0KH-dfZozBKdBw_iGWIxqL0",db=createClient(URL,KEY);
let state={stats:{},orders:[],sellers:[],seller_products:[],deshigram_products:[],fulfillment:[],payouts:[]},listTab="own";
const $=q=>document.querySelector(q), money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(v||0)), fmt=v=>v?new Date(v).toLocaleString("en-IN"):"—", lines=v=>String(v||"").split("\n").map(x=>x.trim()).filter(Boolean), dt=v=>v?new Date(v).toISOString().slice(0,16):"";
const status=(el,msg,type="")=>{el.textContent=msg||"";el.className=`status ${type}`};
async function isAdmin(){const {data:{session}}=await db.auth.getSession();if(!session)return false;const {data,error}=await db.rpc("is_deshigram_admin");return !error&&data===true}
async function boot(){if(await isAdmin()){showApp();await load()}else $("#loginPanel").hidden=false}
function showApp(){$("#loginPanel").hidden=true;$("#adminApp").hidden=false;$("#logoutBtn").hidden=false}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();status($("#loginStatus"),"Signing in…");const f=new FormData(e.currentTarget);const {error}=await db.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(error)return status($("#loginStatus"),error.message,"error");if(!(await isAdmin())){await db.auth.signOut();return status($("#loginStatus"),"Not authorized for DeshiGram Admin.","error")}showApp();await load()});
$("#logoutBtn").addEventListener("click",async()=>{await db.auth.signOut();location.reload()});
async function load(){status($("#appStatus"),"Loading admin data…");const {data,error}=await db.rpc("admin_full_portal_data");if(error)return status($("#appStatus"),error.message,"error");state=data||state;renderAll();status($("#appStatus"),"")}
$("#refreshAll").addEventListener("click",load);
document.querySelectorAll(".side-link").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".side-link").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".section-panel").forEach(x=>x.classList.toggle("active",x.dataset.panel===b.dataset.section));$("#sectionTitle").textContent=b.textContent}));
const pill=v=>`<span class="pill ${v||""}">${String(v||"unknown").replaceAll("_"," ")}</span>`;
function renderAll(){renderStats();renderDashboard();renderOrders();renderFulfillment();renderSellers();renderSellerListings();renderPayouts();renderProducts();renderListingManager()}
function renderStats(){const s=state.stats||{},arr=[["Orders",s.orders],["Revenue",money(s.revenue)],["Pending Orders",s.pending_orders],["Ready Pickup",s.seller_ready],["Seller Reviews",s.sellers_pending],["Payout Available",money(s.payout_available)]];$("#stats").innerHTML=arr.map(([a,b])=>`<div class="stat"><strong>${b??0}</strong><span>${a}</span></div>`).join("")}
function renderDashboard(){const orders=(state.orders||[]).slice(0,6);$("#recentOrders").innerHTML=`<div class="mini-list">${orders.map(o=>`<div class="mini-row"><span><b>${o.order_number}</b><br>${o.customer_name}</span><span>${money(o.total_amount)}<br>${pill(o.order_status)}</span></div>`).join("")||"No orders yet."}</div>`;const a=[];(state.sellers||[]).filter(x=>["pending","under_review"].includes(x.verification_status)).slice(0,4).forEach(x=>a.push(`Seller review: <b>${x.business_name||x.full_name}</b>`));(state.seller_products||[]).filter(x=>x.status==="under_review").slice(0,4).forEach(x=>a.push(`Listing review: <b>${x.name}</b>`));(state.fulfillment||[]).filter(x=>x.fulfillment_status==="ready_for_pickup").slice(0,4).forEach(x=>a.push(`Pickup ready: <b>${x.order_number}</b> • ${x.product_name}`));$("#attention").innerHTML=`<div class="mini-list">${a.map(x=>`<div class="mini-row"><span>${x}</span></div>`).join("")||"Nothing urgent."}</div>`}
function renderOrders(){const q=($("#ordersSearch").value||"").toLowerCase(),st=$("#ordersStatus").value;const rows=(state.orders||[]).filter(o=>(!st||o.order_status===st)&&(!q||`${o.order_number} ${o.customer_name} ${o.phone} ${o.product_name}`.toLowerCase().includes(q)));$("#ordersTable").innerHTML=`<table class="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Products</th><th>Payment</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${o.order_number}</b><br>${o.pincode||""}</td><td>${o.customer_name}<br>${o.phone}</td><td>${o.product_name||""}</td><td>${o.payment_method||""}<br>${pill(o.payment_status)}</td><td>${money(o.total_amount)}</td><td>${pill(o.order_status)}</td><td>${fmt(o.created_at)}</td></tr>`).join("")}</tbody></table>`}
function renderFulfillment(){const q=($("#fulfillmentSearch").value||"").toLowerCase(),st=$("#fulfillmentStatus").value;const rows=(state.fulfillment||[]).filter(x=>(!st||x.fulfillment_status===st)&&(!q||`${x.order_number} ${x.product_name} ${x.tracking_id||""}`.toLowerCase().includes(q)));$("#fulfillmentCards").innerHTML=rows.map(x=>`<article class="card"><span>${pill(x.fulfillment_status)}</span><h3>${x.order_number} • ${x.product_name}</h3><p>${x.seller_business_name||"DeshiGram"} • Qty ${x.quantity}</p><p>${x.courier_name||"Courier not assigned"} • ${x.tracking_id||"No tracking"}</p><p>Customer: ${x.customer_name} • ${x.pincode||""}</p><div class="actions"><button data-fulfill="${x.id}" class="ghost">Update Fulfillment</button></div></article>`).join("")||"<p>No fulfillment items.</p>"}
function renderSellers(){const q=($("#sellerSearch").value||"").toLowerCase(),st=$("#sellerStatus").value;const rows=(state.sellers||[]).filter(x=>(!st||x.verification_status===st)&&(!q||`${x.full_name} ${x.business_name||""} ${x.phone}`.toLowerCase().includes(q)));$("#sellerCards").innerHTML=rows.map(x=>`<article class="card"><span>${pill(x.verification_status)}</span><h3>${x.business_name||x.full_name}</h3><p>${x.full_name} • ${x.phone}</p><p>${x.city||""}, ${x.state||""} • ${x.pincode||""}</p><p>FSSAI: ${x.fssai_number||"—"} • GST: ${x.gstin||"—"}</p><div class="actions"><button class="ghost" data-review-seller="${x.user_id}">Review Seller</button><button class="primary" data-settle="${x.user_id}" data-seller-name="${x.business_name||x.full_name}">Settle Available</button></div></article>`).join("")||"<p>No sellers.</p>"}
function renderSellerListings(){const q=($("#sellerListingSearch").value||"").toLowerCase(),st=$("#sellerListingStatus").value;const rows=(state.seller_products||[]).filter(x=>(!st||x.status===st)&&(!q||`${x.name} ${x.seller_business_name||""}`.toLowerCase().includes(q)));$("#sellerListingCards").innerHTML=rows.map(sellerCard).join("")||"<p>No seller listings.</p>"}
function renderPayouts(){const q=($("#payoutSearch").value||"").toLowerCase(),st=$("#payoutStatus").value;const rows=(state.payouts||[]).filter(x=>(!st||x.status===st)&&(!q||`${x.seller_business_name||""} ${x.reference||""}`.toLowerCase().includes(q)));$("#payoutCards").innerHTML=rows.map(x=>`<article class="card"><span>${pill(x.status)}</span><h3>${x.seller_business_name}</h3><p>${x.period_start||""} → ${x.period_end||""}</p><p>Gross ${money(x.gross_sales)} • Deductions ${money(x.deductions)}</p><p class="price">Net ${money(x.net_payout)}</p><p>Ref: ${x.reference||"—"} • ${fmt(x.paid_at)}</p></article>`).join("")||"<p>No payout records.</p>"}
function ownCard(p){const low=Number(p.stock_quantity||0)<=Number(p.low_stock_threshold||5);return `<article class="card"><span>${pill(p.status)}</span><h3>${p.name}</h3><p>${p.net_quantity||""} • ${p.sku||"No SKU"}</p><p class="price">${money(p.selling_price)} <s>${money(p.mrp)}</s></p><p class="${low?"warn":""}">Stock ${p.stock_quantity}${low?" • Low stock":""}</p><p>${p.badge_text?`Badge: ${p.badge_text} • `:""}${p.featured?"Featured • ":""}${p.is_visible===false?"Hidden":"Visible"}</p><div class="actions"><button class="ghost" data-edit-product="${p.id}">Edit Product</button><button data-merch-own="${p.id}" data-status="coming_soon">Coming Soon</button><button data-merch-own="${p.id}" data-status="live">Go Live</button></div></article>`}
function sellerCard(p){return `<article class="card"><span>${pill(p.status)}</span><h3>${p.name}</h3><p>${p.seller_business_name||"Seller"} • ${p.category||""}</p><p class="price">${money(p.selling_price)} <s>${money(p.mrp)}</s></p><p>Stock ${p.stock_quantity} • Payout ${money(p.seller_payout||p.bank_settlement||0)}</p><div class="actions"><button class="ghost" data-edit-seller-listing="${p.id}">Review / Options</button><button data-review-listing="${p.id}" data-status="live">Approve Live</button><button data-review-listing="${p.id}" data-status="changes_required">Changes</button></div></article>`}
function renderProducts(){const q=($("#productSearch").value||"").toLowerCase(),st=$("#productStatus").value;$("#productCards").innerHTML=(state.deshigram_products||[]).filter(x=>(!st||x.status===st)&&(!q||x.name.toLowerCase().includes(q))).map(ownCard).join("")||"<p>No products.</p>"}
function renderListingManager(){const q=($("#listingSearch").value||"").toLowerCase(),st=$("#listingStatus").value;$("#listingOwn").innerHTML=(state.deshigram_products||[]).filter(x=>(!st||x.status===st)&&(!q||x.name.toLowerCase().includes(q))).map(ownCard).join("")||"<p>No products.</p>";$("#listingSeller").innerHTML=(state.seller_products||[]).filter(x=>(!st||x.status===st)&&(!q||`${x.name} ${x.seller_business_name||""}`.toLowerCase().includes(q))).map(sellerCard).join("")||"<p>No seller listings.</p>"}
["ordersSearch","ordersStatus"].forEach(id=>$("#"+id).addEventListener("input",renderOrders));["fulfillmentSearch","fulfillmentStatus"].forEach(id=>$("#"+id).addEventListener("input",renderFulfillment));["sellerSearch","sellerStatus"].forEach(id=>$("#"+id).addEventListener("input",renderSellers));["sellerListingSearch","sellerListingStatus"].forEach(id=>$("#"+id).addEventListener("input",renderSellerListings));["payoutSearch","payoutStatus"].forEach(id=>$("#"+id).addEventListener("input",renderPayouts));["productSearch","productStatus"].forEach(id=>$("#"+id).addEventListener("input",renderProducts));["listingSearch","listingStatus"].forEach(id=>$("#"+id).addEventListener("input",renderListingManager));
document.querySelectorAll("[data-list-tab]").forEach(b=>b.addEventListener("click",()=>{listTab=b.dataset.listTab;document.querySelectorAll("[data-list-tab]").forEach(x=>x.classList.toggle("active",x===b));$("#listingOwn").hidden=listTab!=="own";$("#listingSeller").hidden=listTab!=="seller"}));
function fill(form,p){[...form.elements].forEach(el=>{if(!el.name)return;const v=p?.[el.name];if(el.type==="checkbox")el.checked=v!==false;else if(el.type==="datetime-local")el.value=dt(v);else if(Array.isArray(v))el.value=v.join("\n");else el.value=v??""})}
$("#newProductBtn").addEventListener("click",()=>{const f=$("#productForm");f.reset();f.id.value="";f.category.value="DeshiGram";f.status.value="draft";f.max_order_quantity.value=10;f.low_stock_threshold.value=5;f.is_visible.checked=true;f.cod_enabled.checked=true;f.online_payment_enabled.checked=true;$("#deleteProductBtn").hidden=true;$("#productDialogTitle").textContent="New Product";$("#productDialog").showModal()});
async function uploadImages(files){const paths=[];for(const file of files){const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-"),path=`admin/${Date.now()}-${crypto.randomUUID().slice(0,8)}-${safe}`;const {error}=await db.storage.from("deshigram-products").upload(path,file,{contentType:file.type||"image/jpeg"});if(error)throw error;paths.push(path)}return paths}
$("#productForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),out=$("#productFormStatus");try{status(out,"Saving…");let images=lines(fd.get("image_paths"));const files=[...$("#imageUpload").files];if(files.length)images=[...images,...await uploadImages(files)];const payload={name:fd.get("name"),slug:fd.get("slug"),sku:fd.get("sku"),category:fd.get("category"),net_quantity:fd.get("net_quantity"),mrp:Number(fd.get("mrp")||0),selling_price:Number(fd.get("selling_price")||0),stock_quantity:Number(fd.get("stock_quantity")||0),packed_weight_grams:Number(fd.get("packed_weight_grams")||0),max_order_quantity:Number(fd.get("max_order_quantity")||10),low_stock_threshold:Number(fd.get("low_stock_threshold")||5),status:fd.get("status"),coming_soon_date:fd.get("coming_soon_date")||null,sort_order:Number(fd.get("sort_order")||100),badge_text:fd.get("badge_text"),offer_type:fd.get("offer_type"),offer_value:Number(fd.get("offer_value")||0),offer_label:fd.get("offer_label"),offer_starts_at:fd.get("offer_starts_at")||null,offer_ends_at:fd.get("offer_ends_at")||null,is_visible:fd.get("is_visible")==="on",featured:fd.get("featured")==="on",cod_enabled:fd.get("cod_enabled")==="on",online_payment_enabled:fd.get("online_payment_enabled")==="on",short_description:fd.get("short_description"),description:fd.get("description"),ingredients:lines(fd.get("ingredients")),features:lines(fd.get("features")),usage_steps:lines(fd.get("usage_steps")),storage_instructions:fd.get("storage_instructions"),image_paths:images,seo_title:fd.get("seo_title"),seo_description:fd.get("seo_description")};const {error}=await db.rpc("admin_save_deshigram_product",{p_id:fd.get("id")||null,p_payload:payload});if(error)throw error;status(out,"Saved.","ok");setTimeout(()=>$("#productDialog").close(),250);await load()}catch(err){status(out,err.message,"error")}});
$("#deleteProductBtn").addEventListener("click",async()=>{const id=$("#productForm").id.value;if(!id||!confirm("Delete this product permanently?"))return;const {error}=await db.rpc("admin_delete_deshigram_product",{p_id:id});if(error)return status($("#productFormStatus"),error.message,"error");$("#productDialog").close();await load()});
async function merch(kind,id,payload){const {error}=await db.rpc("admin_update_listing_merchandising",{p_kind:kind,p_id:id,p_payload:payload});if(error)throw error;await load()}
async function reviewListing(id,statusValue,note="",payout=null){const {error}=await db.rpc("admin_review_seller_product",{p_product_id:id,p_status:statusValue,p_note:note||null,p_seller_payout:payout});if(error)throw error;await load()}
document.addEventListener("click",async e=>{try{const ep=e.target.closest("[data-edit-product]");if(ep){const p=state.deshigram_products.find(x=>x.id===ep.dataset.editProduct);fill($("#productForm"),p);$("#productDialogTitle").textContent=p.name;$("#deleteProductBtn").hidden=false;$("#productDialog").showModal();return}const es=e.target.closest("[data-edit-seller-listing]");if(es){const p=state.seller_products.find(x=>x.id===es.dataset.editSellerListing);fill($("#sellerForm"),p);$("#sellerTitle").textContent=p.name;$("#sellerDialog").showModal();return}const mo=e.target.closest("[data-merch-own]");if(mo){await merch("deshigram",mo.dataset.merchOwn,{status:mo.dataset.status,is_visible:true});return}const rl=e.target.closest("[data-review-listing]");if(rl){await reviewListing(rl.dataset.reviewListing,rl.dataset.status);return}const fs=e.target.closest("[data-fulfill]");if(fs){const x=state.fulfillment.find(v=>v.id===fs.dataset.fulfill);$("#fulfillmentForm").item_id.value=x.id;$("#fulfillmentForm").status.value=x.fulfillment_status||"pending";$("#fulfillmentForm").courier.value=x.courier_name||"";$("#fulfillmentForm").tracking_id.value=x.tracking_id||"";$("#fulfillmentTitle").textContent=`${x.order_number} • ${x.product_name}`;$("#fulfillmentDialog").showModal();return}const rs=e.target.closest("[data-review-seller]");if(rs){const x=state.sellers.find(v=>v.user_id===rs.dataset.reviewSeller);$("#sellerReviewForm").seller_id.value=x.user_id;$("#sellerReviewForm").status.value=x.verification_status||"under_review";$("#sellerReviewForm").note.value=x.verification_note||"";$("#sellerReviewTitle").textContent=x.business_name||x.full_name;$("#sellerReviewDialog").showModal();return}const st=e.target.closest("[data-settle]");if(st){$("#settlementForm").seller_id.value=st.dataset.settle;$("#settlementTitle").textContent=`Settle • ${st.dataset.sellerName}`;$("#settlementDialog").showModal();return}}catch(err){status($("#appStatus"),err.message,"error")}});
$("#fulfillmentForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await db.rpc("admin_update_fulfillment_item",{p_item_id:f.get("item_id"),p_status:f.get("status"),p_courier:f.get("courier")||null,p_tracking_id:f.get("tracking_id")||null});if(error)return status($("#fulfillmentFormStatus"),error.message,"error");$("#fulfillmentDialog").close();await load()});
$("#sellerReviewForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await db.rpc("admin_review_seller",{p_seller_id:f.get("seller_id"),p_status:f.get("status"),p_note:f.get("note")||null});if(error)return status($("#sellerReviewStatus"),error.message,"error");$("#sellerReviewDialog").close();await load()});
$("#settlementForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {data,error}=await db.rpc("admin_settle_seller_available",{p_seller_id:f.get("seller_id"),p_reference:f.get("reference")});if(error)return status($("#settlementStatus"),error.message,"error");status($("#settlementStatus"),`Settlement saved: ${JSON.stringify(data)}`,"ok");setTimeout(()=>$("#settlementDialog").close(),600);await load()});
$("#sellerForm").addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),out=$("#sellerFormStatus"),id=fd.get("id");try{status(out,"Saving…");await reviewListing(id,fd.get("status"),fd.get("review_note"),fd.get("seller_payout")===""?null:Number(fd.get("seller_payout")));await merch("seller",id,{status:fd.get("status"),coming_soon_date:fd.get("coming_soon_date")||null,badge_text:fd.get("badge_text"),offer_type:fd.get("offer_type"),offer_value:Number(fd.get("offer_value")||0),offer_label:fd.get("offer_label"),offer_starts_at:fd.get("offer_starts_at")||null,offer_ends_at:fd.get("offer_ends_at")||null,max_order_quantity:Number(fd.get("max_order_quantity")||10),low_stock_threshold:Number(fd.get("low_stock_threshold")||5),is_visible:fd.get("is_visible")==="on",featured:fd.get("featured")==="on",cod_enabled:fd.get("cod_enabled")==="on",online_payment_enabled:fd.get("online_payment_enabled")==="on"});status(out,"Saved.","ok");$("#sellerDialog").close();await load()}catch(err){status(out,err.message,"error")}});
boot();
