document.addEventListener("DOMContentLoaded",()=>{
  const cart=window.DESHIGRAM_CART;const itemsEl=document.getElementById("checkoutItems"),mrpEl=document.getElementById("checkoutMrpTotal"),discountEl=document.getElementById("checkoutDiscount"),totalEl=document.getElementById("checkoutTotal"),form=document.getElementById("checkoutForm"),status=document.getElementById("checkoutStatus"),confirmButton=document.getElementById("confirmPaymentButton"),payButton=document.getElementById("payWithUpiButton"),qrFallback=document.getElementById("upiQrFallback");
  const FEES={logistics:55,platform:10,packaging:5,payment:5};const feeTotal=Object.values(FEES).reduce((a,b)=>a+b,0);const upiId="singh.abhinendra5@ybl",receiverName="Mr Abhinendra Singh";const money=value=>cart.money?cart.money(value):`₹${Number(value).toFixed(2)}`;
  const totals=()=>{const product=cart.getSubtotal(),mrp=cart.getMrpTotal?cart.getMrpTotal():product/0.7,discount=mrp-product,total=product+feeTotal;return{product,mrp,discount,total};};
  function upiLink(){const {total}=totals();return `upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(receiverName)}&am=${total.toFixed(2)}&cu=INR&tn=${encodeURIComponent("DeshiGram order payment")}`;}
  function render(){const items=cart.getCart();if(!items.length){itemsEl.innerHTML='<div class="checkout-empty"><p>Your cart is empty.</p><a href="products.html">Choose a pack</a></div>';confirmButton.disabled=true;payButton.disabled=true;mrpEl.textContent=discountEl.textContent=totalEl.textContent=money(0);return;}confirmButton.disabled=false;payButton.disabled=false;itemsEl.innerHTML=items.map(item=>`<article class="checkout-item"><img src="${item.image}" alt="${item.name}"><div><h3>${item.name}</h3><p>${item.weight} × ${item.quantity}</p><small>30% off MRP</small></div><strong>${money(item.price*item.quantity)}</strong></article>`).join("");const t=totals();mrpEl.textContent=money(t.mrp);discountEl.textContent=`− ${money(t.discount)}`;totalEl.textContent=money(t.total);}
  function customerData(){return Object.fromEntries(new FormData(form).entries());}
  function validForm(){if(!form.reportValidity())return false;if(!cart.getCart().length){status.textContent="Your cart is empty.";return false;}return true;}
  function orderLines(){return cart.getCart().map(item=>`• ${item.name} (${item.weight}) × ${item.quantity} = ${money(item.price*item.quantity)}`);}
  function openWhatsapp(message){window.open(`https://wa.me/919457831399?text=${encodeURIComponent(message)}`,"_blank","noopener");}
  payButton.addEventListener("click",()=>{if(!cart.getCart().length)return;window.location.href=upiLink();setTimeout(()=>{qrFallback.hidden=false;},900);});
  form.addEventListener("submit",event=>{event.preventDefault();if(!validForm())return;const c=customerData(),t=totals();const msg=`Hello DeshiGram, I have completed the UPI payment and want to confirm my order.\n\n${orderLines().join("\n")}\n\nMRP total: ${money(t.mrp)}\n30% discount: -${money(t.discount)}\nLogistics / delivery: ₹55.00\nPlatform handling: ₹10.00\nSecure packaging: ₹5.00\nPayment handling: ₹5.00\nTotal paid: ${money(t.total)}\nUPI ID: ${upiId}\nTransaction ID / UTR: ${c.transactionId}\n\nCustomer Details:\nName: ${c.name}\nPhone: ${c.phone}\nEmail: ${c.email||"Not provided"}\nAddress: ${c.address}, ${c.city}, ${c.state} - ${c.pincode}`;status.innerHTML='Opening WhatsApp to send your order confirmation.';openWhatsapp(msg);});
  document.addEventListener("deshigram:cart-updated",render);render();
});