document.addEventListener("DOMContentLoaded",async()=>{
 const id=new URLSearchParams(location.search).get("id")||"pack-1", err=document.getElementById("productError");
 const products=await window.DESHIGRAM_CATALOG.load(); const p=products.find(x=>x.id===id);
 if(!p){err.hidden=false;return} document.getElementById("productDetailPage").hidden=false; document.title=p.name+" | DeshiGram";
 let details={}; try{const U='https://kqkpbqpfnupjpthtpvdn.supabase.co',K='sb_publishable_AVVPm0Pr0KH-dfZozBKdBw_iGWIxqL0';const r=await fetch(`${U}/rest/v1/product_details?product_key=eq.${encodeURIComponent(p.slug||p.id)}&select=*`,{headers:{apikey:K,Authorization:`Bearer ${K}`}});if(r.ok)details=(await r.json())[0]||{}}catch(_){}
 const $=s=>document.querySelector(s), set=(s,v)=>{const e=$(s);if(e)e.textContent=v||""}, money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(v||0));
 set("#breadcrumbName",p.name);set("#productName",p.name);set("#productWeight",p.weight);set("#productBrand",details.brand||"DeshiGram");
 if(Number(p.price)>0){set("#productPrice",money(p.price));set("#productOldPrice",p.oldPrice>p.price?`MRP ${money(p.oldPrice)}`:"");if(p.oldPrice>p.price)set("#productDiscount",`${Math.round((p.oldPrice-p.price)/p.oldPrice*100)}% OFF`)}else set("#productPrice","Price updating");
 set("#productStock",p.stock_quantity>0?`In stock: ${p.stock_quantity}`:"Stock status will be updated");
 const main=$("#mainProductImage"),thumbs=$("#productThumbnails"),imgs=(p.images||[]).filter(Boolean);main.src=imgs[0]||"images/favicon.png";main.alt=p.name;
 imgs.forEach((src,i)=>{const b=document.createElement("button");b.className="dg-v3-thumb"+(i?"":" active");b.innerHTML=`<img src="${src}" alt="${p.name} ${i+1}">`;b.onclick=()=>{main.src=src;thumbs.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active")};thumbs.appendChild(b)});
 const add=$("#addProductToCart"),unavailable=p.status!=="live"||p.stock_quantity<=0||Number(p.price)<=0;add.disabled=unavailable;add.textContent=Number(p.price)<=0?"Price updating":unavailable?"Out of Stock":"Add to Cart";if(!unavailable){add.dataset.addToCart=p.id;add.onclick=()=>window.DESHIGRAM_CART?.add(p.id,1)}
 const highlights={"Brand":details.brand||"DeshiGram","Product Type":details.product_type,"Dietary Preference":details.dietary_preference,"Spice Level":details.spice_level,"Flavour":details.flavour,"Weight":details.weight||p.weight,"Key Features":details.key_features||(p.features||[]).join(", "),"Unit":details.unit,"Ingredients":details.ingredients||(p.ingredients||[]).join(", "),"Allergen Information":details.allergen_information,"FSSAI License":details.fssai_license,"Nutrition Information":details.nutrition_information,"Cuisine Type":details.cuisine_type,"Packaging Type":details.packaging_type,"Storage Instruction":details.storage_instruction||p.storage,"Processing Type":details.processing_type,"Specialty":details.specialty};
 const info={"Disclaimer":details.disclaimer,"Customer Care":details.customer_care,"Manufacturer / Marketer":details.manufacturer_marketer,"Country of Origin":details.country_of_origin,"Shelf Life":details.shelf_life};
 function fill(el,obj){Object.entries(obj).filter(([,v])=>String(v||"").trim()).forEach(([k,v])=>el.insertAdjacentHTML("beforeend",`<dt>${k}</dt><dd>${String(v).replace(/\n/g,"<br>")}</dd>`))}
 fill($("#productHighlights"),highlights);fill($("#productInfo"),info);if(!$("#productInfo").children.length)$("#productInfo").innerHTML="<dt>Information</dt><dd>Verified product information can be updated from DeshiGram Admin.</dd>";
 const more=$("#moreProducts");products.filter(x=>x.id!==p.id).slice(0,10).forEach(x=>more.insertAdjacentHTML("beforeend",`<a class="dg-v3-more-card" href="product/index.html?id=${encodeURIComponent(x.id)}"><img src="${x.images?.[0]||'images/favicon.png'}"><b>${x.name}</b><small>${x.weight||""}</small></a>`));
});