function logisticsFor(weightGrams){
  const g = Number(weightGrams) || 0;
  if (g <= 0) return 0;
  // Locked DeshiGram rule: first 500g = ₹80, every started extra 500g = +₹30.
  return 80 + (Math.ceil(g / 500) - 1) * 30;
}
document.addEventListener('DOMContentLoaded', async()=>{
  const SUPABASE_URL='https://kqkpbqpfnupjpthtpvdn.supabase.co';
  const SUPABASE_KEY='sb_publishable_AVVPm0Pr0KH-dfZozBKdBw_iGWIxqL0';
  const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=id=>document.getElementById(id); const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(v||0));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cleanPhone=v=>String(v||'').replace(/\D/g,'').slice(-10); const sellerEmail=p=>`${cleanPhone(p)}@seller.deshigram.in`;
  let profile=null, products=[], orders=[], payouts=[], documents=[];
  function setStatus(el,msg,type=''){if(!el)return;el.textContent=msg||'';el.classList.remove('is-error','is-success');if(type)el.classList.add(type==='error'?'is-error':'is-success');}

  function showLogin(){
    $('loginCard').hidden=false; $('signupCard').hidden=true;
    setStatus($('sellerAuthStatus'),''); setStatus($('sellerSignupStatus'),'');
  }
  function showSignup(){
    $('loginCard').hidden=true; $('signupCard').hidden=false;
    setStatus($('sellerAuthStatus'),''); setStatus($('sellerSignupStatus'),'');
  }
  $('showSignup').addEventListener('click',showSignup);
  $('backToLogin').addEventListener('click',showLogin);

  function setView(name){
    document.querySelectorAll('[data-view-panel]').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===name));
    document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));
    $('sellerSidebar')?.classList.remove('open');
    window.scrollTo({top:0,behavior:'smooth'});
  }
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
  document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));
  $('mobileMenuBtn')?.addEventListener('click',()=> $('sellerSidebar')?.classList.toggle('open'));

  async function session(){const {data}=await sb.auth.getSession();return data.session;}
  async function user(){const s=await session();return s?.user||null;}
  function logisticsCharge(g){g=Number(g)||0;if(g<=0)return 0;return 80+(Math.ceil(g/500)-1)*30}
  function listingPrice(settlement,g){return Number(settlement||0)+logisticsCharge(g)+10+3}
  function updatePricePreview(){const f=$('sellerProductForm');if(!f)return;const settlement=Number(f.elements.bank_settlement?.value)||0, grams=Number(f.elements.packed_weight_grams?.value)||0, logistics=logisticsCharge(grams), total=listingPrice(settlement,grams);[['listingPricePreview',total],['priceSettlement',settlement],['priceLogistics',logistics],['priceTotal',total]].forEach(([id,v])=>{const e=$(id);if(e)e.textContent=money(v)})}
  function badgeStatus(v){return String(v||'pending').replace(/_/g,' ')}

  async function ensureSellerProfile(meta={}){const u=await user();if(!u)return null;let {data,error}=await sb.from('seller_profiles').select('*').eq('user_id',u.id).maybeSingle();if(error)throw error;if(!data){const row={user_id:u.id,full_name:meta.full_name||u.user_metadata?.full_name||'Seller',phone:cleanPhone(meta.phone||u.user_metadata?.phone),business_name:meta.business_name||u.user_metadata?.business_name||null};const ins=await sb.from('seller_profiles').insert(row).select().single();if(ins.error)throw ins.error;data=ins.data;}return data;}
  async function refresh(){profile=await ensureSellerProfile();if(!profile)return showAuth();const u=await user();const [pr,or,pa,dc]=await Promise.all([sb.from('seller_products').select('*').eq('seller_id',u.id).order('created_at',{ascending:false}),sb.rpc('seller_order_items'),sb.from('seller_payouts').select('*').eq('seller_id',u.id).order('created_at',{ascending:false}),sb.from('seller_documents').select('*').eq('seller_id',u.id).order('created_at',{ascending:false})]);[pr,or,pa,dc].forEach(r=>{if(r.error)throw r.error});products=pr.data||[];orders=(or.data||[]).map(o=>({...o,id:o.item_id,seller_payout:Number(o.seller_payout_unit||0)*Number(o.quantity||0),total_amount:Number(o.unit_price||0)*Number(o.quantity||0)}));payouts=pa.data||[];documents=dc.data||[];render();showDashboard();}
  function showAuth(){$('sellerAuth').hidden=false;$('sellerDashboard').hidden=true} function showDashboard(){$('sellerAuth').hidden=true;$('sellerDashboard').hidden=false}

  function render(){
    $('sellerName').textContent=profile.business_name||profile.full_name||'Seller';$('sideBusinessName').textContent=profile.business_name||profile.full_name||'DeshiGram Partner';const vs=profile.verification_status||'pending';$('sellerVerificationBadge').className=`status-pill ${vs}`;$('sellerVerificationBadge').textContent=badgeStatus(vs);$('sellerVerificationText').textContent=vs==='approved'?'Your seller account is approved. You can submit products for review.':vs==='changes_required'?(profile.verification_note||'Please update the requested account details.'):'Complete your details and documents for seller verification.';
    const completed=orders.filter(o=>o.order_status==='delivered');$('sellerTotalSales').textContent=money(completed.reduce((s,o)=>s+Number(o.seller_payout||o.total_amount||0),0));$('sellerTotalOrders').textContent=orders.length;$('sellerLiveProducts').textContent=products.filter(p=>p.status==='live').length;$('sellerPendingPayout').textContent=money(orders.filter(o=>o.payout_status==='available').reduce((s,o)=>s+Number(o.seller_payout||0),0)+payouts.filter(p=>['pending','processing'].includes(p.status)).reduce((s,p)=>s+Number(p.net_payout||0),0));
    const actions=[];if(!profile.pickup_address||!profile.city||!profile.pincode)actions.push(['Complete pickup address','Add your pickup address so orders can be collected.']);if(!profile.fssai_number)actions.push(['Add FSSAI details','FSSAI details are required for food seller verification.']);if(!documents.some(d=>d.document_type==='fssai'))actions.push(['Upload FSSAI document','Upload your FSSAI registration/licence document.']);const changeProducts=products.filter(p=>p.status==='changes_required');if(changeProducts.length)actions.push([`${changeProducts.length} listing${changeProducts.length>1?'s':''} need changes`,'Open Products to see the review reason and resubmit.']);const prep=orders.filter(o=>['new','accepted'].includes(o.fulfillment_status));if(prep.length)actions.push([`${prep.length} order${prep.length>1?'s':''} need preparation`,'Prepare the products and mark them ready for pickup.']);$('sellerActions').innerHTML=actions.length?actions.map(a=>`<div class="seller-action"><span class="dot"></span><div><b>${esc(a[0])}</b><small>${esc(a[1])}</small></div></div>`).join(''):'<div class="seller-empty">No action required right now.</div>';
    const counts={live:0,under_review:0,changes_required:0,rejected:0};products.forEach(p=>{if(counts[p.status]!==undefined)counts[p.status]++});$('sellerProductSummary').innerHTML=`<div><span>Live</span><strong>${counts.live}</strong></div><div><span>Under Review</span><strong>${counts.under_review}</strong></div><div><span>Changes Required</span><strong>${counts.changes_required}</strong></div><div><span>Rejected</span><strong>${counts.rejected}</strong></div>`;
    renderProducts();renderOrders();renderPayouts();renderProfile();renderDocuments();
    $('sellerRecentOrders').innerHTML=orders.length?orderTable(orders.slice(0,5)):'<div class="seller-empty">No orders yet.</div>';
  }
  function imageUrl(path){if(!path)return 'images/favicon.png';return sb.storage.from('seller-products').getPublicUrl(path).data.publicUrl}
  function renderProducts(){$('sellerProductsList').innerHTML=products.length?products.map((p,i)=>`<article class="seller-product-card"><img src="${esc(imageUrl(p.image_paths?.[0]))}" alt=""><div><span class="product-status ${esc(p.status)}">${esc(badgeStatus(p.status))}</span><h3>${esc(p.name)}</h3><p>${esc(p.net_quantity)} • MRP ${money(p.mrp)} • Sell ${money(p.selling_price)} • Stock ${esc(p.stock_quantity)}</p>${p.review_note?`<p class="note"><b>Review:</b> ${esc(p.review_note)}</p>`:''}</div><div class="seller-product-actions"><button class="soft-btn" data-edit-product="${i}">Edit</button>${['draft','changes_required','rejected'].includes(p.status)?`<button class="primary-btn compact" data-resubmit-product="${i}">Resubmit</button>`:''}</div></article>`).join(''):'<div class="seller-empty content-card"><h3>No products yet</h3><p>Add your first product and submit it for review.</p></div>';document.querySelectorAll('[data-edit-product]').forEach(b=>b.addEventListener('click',()=>openProduct(products[Number(b.dataset.editProduct)])));document.querySelectorAll('[data-resubmit-product]').forEach(b=>b.addEventListener('click',()=>resubmit(products[Number(b.dataset.resubmitProduct)])));}
  function orderTable(rows){return `<div class="seller-table-card"><table class="seller-table"><thead><tr><th>Order</th><th>Product</th><th>Qty</th><th>Fulfilment</th><th>Payment</th><th>Settlement</th><th>Action</th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${esc(o.order_number)}</b><br><small>${new Date(o.created_at).toLocaleDateString('en-IN')}</small></td><td>${esc(o.product_name)}</td><td>${esc(o.quantity)}</td><td>${esc(badgeStatus(o.fulfillment_status||'new'))}${o.tracking_id?`<br><small>${esc(o.courier_name||'Courier')} • ${esc(o.tracking_id)}</small>`:''}</td><td>${esc(badgeStatus(o.payment_status))}</td><td><b>${money(o.seller_payout||0)}</b><br><small>${esc(badgeStatus(o.payout_status||'pending'))}</small></td><td>${o.fulfillment_status==='new'?`<button class="soft-btn" data-accept-order="${esc(o.id)}">Accept</button>`:o.fulfillment_status==='accepted'?`<button class="primary-btn compact" data-ready-order="${esc(o.id)}">Ready for Pickup</button>`:['ready','pickup_booked','picked_up','shipped'].includes(o.fulfillment_status)?'<span class="status-pill approved">Pickup in progress</span>':'—'}</td></tr>`).join('')}</tbody></table></div>`}
  function renderOrders(){$('sellerOrdersList').innerHTML=orders.length?orderTable(orders):'<div class="seller-empty">No seller orders yet.</div>';document.querySelectorAll('[data-ready-order]').forEach(b=>b.addEventListener('click',()=>markReady(b.dataset.readyOrder)));document.querySelectorAll('[data-accept-order]').forEach(b=>b.addEventListener('click',()=>acceptOrder(b.dataset.acceptOrder)));}
  function renderPayouts(){$('sellerPayoutList').innerHTML=payouts.length?`<table class="seller-table"><thead><tr><th>Period</th><th>Gross</th><th>Deductions</th><th>Net Payout</th><th>Status</th><th>Reference</th></tr></thead><tbody>${payouts.map(p=>`<tr><td>${esc(p.period_start||'—')} → ${esc(p.period_end||'—')}</td><td>${money(p.gross_sales)}</td><td>${money(p.deductions)}</td><td><b>${money(p.net_payout)}</b></td><td>${esc(badgeStatus(p.status))}</td><td>${esc(p.reference||'—')}</td></tr>`).join('')}</tbody></table>`:'<div class="seller-empty">No settlement records yet.</div>'}
  function renderProfile(){const f=$('sellerProfileForm');['full_name','business_name','phone','pickup_address','city','state','pincode','fssai_number','fssai_expiry','pan','gstin'].forEach(k=>{if(f.elements[k])f.elements[k].value=profile[k]||''})}
  function renderDocuments(){$('sellerDocumentList').innerHTML=documents.length?documents.map(d=>`<div class="seller-doc-item"><span><b>${esc(d.document_type.toUpperCase())}</b>${d.review_note?`<br><small>${esc(d.review_note)}</small>`:''}</span><span class="product-status ${esc(d.status)}">${esc(badgeStatus(d.status))}</span></div>`).join(''):'<div class="seller-empty">No documents uploaded.</div>'}

  $('sellerLoginForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('sellerAuthStatus');setStatus(st,'Logging in…');try{const d=Object.fromEntries(new FormData(e.currentTarget));const {error}=await sb.auth.signInWithPassword({email:sellerEmail(d.phone),password:d.password});if(error)throw error;await refresh();setStatus(st,'');}catch(err){setStatus(st,err.message||'Login failed','error');}});
  $('sellerSignupForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('sellerSignupStatus'),d=Object.fromEntries(new FormData(e.currentTarget));if(cleanPhone(d.phone).length!==10){setStatus(st,'Enter a valid 10-digit mobile number.','error');return}if(d.password!==d.confirm_password){setStatus(st,'Passwords do not match.','error');return}setStatus(st,'Creating seller account…');try{const {data,error}=await sb.auth.signUp({email:sellerEmail(d.phone),password:d.password,options:{data:{full_name:d.full_name,business_name:d.business_name,phone:cleanPhone(d.phone),account_type:'seller'}}});if(error)throw error;if(!data.session){setStatus(st,'Account created. Please login.','success');showLogin();setStatus($('sellerAuthStatus'),'Account created. Login to continue.','success');return}await ensureSellerProfile(d);await refresh();setView('account');$('sellerProfileStatus').textContent='Complete your business details and upload FSSAI document for verification.';}catch(err){setStatus(st,err.message||'Account could not be created','error');}});
  $('sellerLogout').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
  $('sellerProfileForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('sellerProfileStatus'),d=Object.fromEntries(new FormData(e.currentTarget));st.textContent='Saving…';try{const u=await user();delete d.phone;const {error}=await sb.from('seller_profiles').update({...d,updated_at:new Date().toISOString()}).eq('user_id',u.id);if(error)throw error;st.textContent='Details saved.';await refresh();}catch(err){setStatus(st,err.message||'Something went wrong.','error')}});
  $('sellerDocumentForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('sellerDocumentStatus'),fd=new FormData(e.currentTarget),type=fd.get('document_type'),file=fd.get('file');st.textContent='Uploading…';try{const u=await user();const ext=(file.name.split('.').pop()||'file').replace(/[^a-z0-9]/gi,'');const path=`${u.id}/${type}/${Date.now()}.${ext}`;const up=await sb.storage.from('seller-documents').upload(path,file,{upsert:false});if(up.error)throw up.error;const current=documents.find(x=>x.document_type===type);let error;if(current){({error}=await sb.from('seller_documents').update({storage_path:path,updated_at:new Date().toISOString()}).eq('id',current.id).eq('seller_id',u.id));}else{({error}=await sb.from('seller_documents').insert({seller_id:u.id,document_type:type,storage_path:path,status:'pending'}));}if(error)throw error;st.textContent='Document uploaded.';e.currentTarget.reset();await refresh();}catch(err){setStatus(st,err.message||'Something went wrong.','error')}});

  function openProduct(p=null){const f=$('sellerProductForm');f.reset();f.product_id.value=p?.id||'';$('productModalTitle').textContent=p?'Edit Listing':'Add Listing';['name','category','description','ingredients','allergen_info','net_quantity','mrp','bank_settlement','packed_weight_grams','package_length_cm','package_width_cm','package_height_cm','shelf_life','stock_quantity','storage_instructions'].forEach(k=>{if(p&&f.elements[k])f.elements[k].value=(k==='bank_settlement'?(p.bank_settlement??p.seller_payout??''):p[k]??'')});$('existingProductImages').innerHTML=(p?.image_paths||[]).map(path=>`<img src="${esc(imageUrl(path))}" alt="">`).join('');$('sellerProductStatus').textContent=p?.review_note?`Last review: ${p.review_note}`:'';updatePricePreview();$('productModal').hidden=false;document.body.style.overflow='hidden'}
  function closeProduct(){$('productModal').hidden=true;document.body.style.overflow=''}$('openAddProduct').addEventListener('click',()=>openProduct());document.querySelectorAll('[data-close-product]').forEach(x=>x.addEventListener('click',closeProduct));
  async function uploadImages(files){const u=await user(),out=[];for(const file of Array.from(files||[]).slice(0,4)){const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'');const path=`${u.id}/${Date.now()}-${Math.random().toString(36).slice(2,7)}.${ext}`;const r=await sb.storage.from('seller-products').upload(path,file,{upsert:false});if(r.error)throw r.error;out.push(path)}return out}
  $('sellerProductForm').elements.bank_settlement?.addEventListener('input',updatePricePreview);$('sellerProductForm').elements.packed_weight_grams?.addEventListener('input',updatePricePreview);$('priceDetailToggle')?.addEventListener('click',()=>{const p=$('priceDetailPanel');p.hidden=!p.hidden;$('priceDetailToggle').textContent=p.hidden?'See details':'Hide details'});
  $('sellerProductForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('sellerProductStatus'),f=e.currentTarget,d=Object.fromEntries(new FormData(f)),id=d.product_id;setStatus(st,'Submitting for review…');try{const u=await user(),existing=id?products.find(x=>x.id===id):null,newImgs=await uploadImages(f.images.files),payload={seller_id:u.id,name:d.name.trim(),category:d.category,description:d.description.trim(),ingredients:d.ingredients.trim(),allergen_info:d.allergen_info.trim()||null,net_quantity:d.net_quantity.trim(),mrp:Number(d.mrp),bank_settlement:Number(d.bank_settlement),seller_payout:Number(d.bank_settlement),packed_weight_grams:Number(d.packed_weight_grams),package_length_cm:Number(d.package_length_cm),package_width_cm:Number(d.package_width_cm),package_height_cm:Number(d.package_height_cm),logistics_charge:logisticsCharge(Number(d.packed_weight_grams)),platform_fee:10,payment_processing_fee:3,selling_price:listingPrice(Number(d.bank_settlement),Number(d.packed_weight_grams)),shelf_life:d.shelf_life.trim(),stock_quantity:Number(d.stock_quantity||0),storage_instructions:d.storage_instructions.trim()||null,image_paths:[...(existing?.image_paths||[]),...newImgs].slice(0,4),status:'under_review',review_note:null,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(id){delete payload.seller_id;const r=await sb.from('seller_products').update(payload).eq('id',id).eq('seller_id',u.id);if(r.error)throw r.error}else{const r=await sb.from('seller_products').insert(payload);if(r.error)throw r.error}setStatus(st,'Submitted for review.','success');await refresh();setTimeout(closeProduct,650);}catch(err){setStatus(st,err.message||'Something went wrong.','error')}});
  async function resubmit(p){try{const u=await user();const r=await sb.from('seller_products').update({status:'under_review',review_note:null,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',p.id).eq('seller_id',u.id);if(r.error)throw r.error;await refresh();}catch(err){alert(err.message)}}
  async function acceptOrder(id){try{const r=await sb.rpc('seller_accept_order_item',{p_item_id:id});if(r.error)throw r.error;await refresh();}catch(err){alert(err.message)}}
  async function markReady(id){try{const r=await sb.rpc('seller_mark_item_ready',{p_item_id:id});if(r.error)throw r.error;await refresh();}catch(err){alert(err.message)}}

  showLogin();try{if(await session())await refresh();else showAuth();}catch(err){console.error(err);setStatus($('sellerAuthStatus'),'Seller login is temporarily unavailable. Please try again shortly.','error');showAuth();}
});
