-- DeshiGram private dashboard + first-party visitor counter
-- Run once in Supabase > SQL Editor after the previous setup.

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_key text not null,
  path text,
  referrer text,
  created_at timestamptz not null default now()
);

alter table public.site_visits enable row level security;
-- No public SELECT/INSERT policies. Public writes happen only through the secured RPC below.

create or replace function public.track_site_visit(
  p_visitor_key text,
  p_path text default '/',
  p_referrer text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(p_visitor_key),'') = '' then return; end if;
  insert into public.site_visits(visitor_key, path, referrer)
  values (
    left(trim(p_visitor_key),120),
    left(trim(coalesce(p_path,'/')),500),
    left(trim(coalesce(p_referrer,'')),500)
  );
end;
$$;

revoke all on function public.track_site_visit(text,text,text) from public;
grant execute on function public.track_site_visit(text,text,text) to anon, authenticated;

create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(coalesce(auth.jwt()->>'email',''));
  v_result jsonb;
begin
  if v_email <> 'deshigramofficial@gmail.com' then
    raise exception 'Not authorized';
  end if;

  select jsonb_build_object(
    'visitors_total', (select count(distinct visitor_key) from public.site_visits),
    'visitors_today', (select count(distinct visitor_key) from public.site_visits where created_at >= date_trunc('day', now() at time zone 'Asia/Kolkata') at time zone 'Asia/Kolkata'),
    'visitors_month', (select count(distinct visitor_key) from public.site_visits where created_at >= date_trunc('month', now() at time zone 'Asia/Kolkata') at time zone 'Asia/Kolkata'),
    'pageviews_total', (select count(*) from public.site_visits),
    'orders_total', (select count(*) from public.orders),
    'orders_today', (select count(*) from public.orders where created_at >= date_trunc('day', now() at time zone 'Asia/Kolkata') at time zone 'Asia/Kolkata'),
    'sales_total', (select coalesce(sum(total_amount),0) from public.orders where order_status <> 'cancelled'),
    'reviews_total', (select count(*) from public.reviews where status='approved'),
    'average_rating', (select coalesce(round(avg(rating)::numeric,1),0) from public.reviews where status='approved'),
    'latest_orders', coalesce((
      select jsonb_agg(x) from (
        select order_number, customer_name, phone, product_name, quantity, total_amount, payment_status, order_status, created_at
        from public.orders order by created_at desc limit 10
      ) x
    ), '[]'::jsonb),
    'latest_reviews', coalesce((
      select jsonb_agg(x) from (
        select name, rating, review, verified, created_at
        from public.reviews where status='approved' order by created_at desc limit 10
      ) x
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

revoke all on function public.admin_dashboard_stats() from public;
grant execute on function public.admin_dashboard_stats() to authenticated;
