
(()=>{const p=new URLSearchParams(location.search),id=p.get('id')||'',name=p.get('name')||'DeshiGram Product',img=p.get('image')||'',price=p.get('price')||'';
const known={
'panch-poshan-seed-powder':{name:'Panch Poshan Seed Powder',image:'images/panch-poshan-pack-1.png',unit:'100 g',brand:'DeshiGram',type:'Seed Powder',diet:'Veg',packaging:'Pouch',features:'Blend of five seeds',gallery:['images/panch-poshan-pack-1.png','images/panch-poshan-pack-2.png','images/panch-poshan-pack-3.png']},
'panch-poshan-seed-powder-pack-of-2':{name:'Panch Poshan Seed Powder – Pack of 2',image:'images/panch-poshan-pack-2.png',unit:'2 × 100 g',brand:'DeshiGram',type:'Seed Powder',diet:'Veg',packaging:'Pouch',features:'Pack of 2',gallery:['images/panch-poshan-pack-2.png','images/panch-poshan-pack-1.png','images/panch-poshan-pack-3.png']},
'panch-poshan-seed-powder-pack-of-3':{name:'Panch Poshan Seed Powder – Pack of 3',image:'images/panch-poshan-pack-3.png',unit:'3 × 100 g',brand:'DeshiGram',type:'Seed Powder',diet:'Veg',packaging:'Pouch',features:'Pack of 3',gallery:['images/panch-poshan-pack-3.png','images/panch-poshan-pack-1.png','images/panch-poshan-pack-2.png']},
'dry-fruits-energy-powder':{name:'Dry Fruits Energy Powder',image:'images/dry-fruits-original.png',unit:'100 g',brand:'DeshiGram',type:'Dry Fruits Powder',diet:'Veg',packaging:'Pouch',gallery:['images/dry-fruits-original.png']}
};let k=known[id]||Object.values(known).find(x=>name.toLowerCase().includes(x.name.split(' – ')[0].toLowerCase()))||{name,image:img,unit:'',brand:'DeshiGram',gallery:[img].filter(Boolean)};
document.title=k.name+' | DeshiGram';document.querySelector('#dgName').textContent=k.name;document.querySelector('#dgBrand').textContent=k.brand||'DeshiGram';document.querySelector('#dgUnit').textContent=k.unit||'';document.querySelector('#dgPrice').textContent=price||'See current price';document.querySelector('#dgMainImage').src=k.image||img||'images/deshigram-wordmark.png';
let thumbs=document.querySelector('#dgThumbs');(k.gallery||[k.image]).filter(Boolean).forEach(x=>{let im=document.createElement('img');im.src=x;im.onclick=()=>document.querySelector('#dgMainImage').src=x;thumbs.appendChild(im)});
let hi={Brand:k.brand||'DeshiGram','Product Type':k.type,'Dietary Preference':k.diet,Weight:k.unit,'Key Features':k.features,'Packaging Type':k.packaging};let info={'Country Of Origin':'India','Ingredients':k.ingredients,'Allergen Information':k.allergen,'FSSAI License':k.fssai,'Nutrition Information':k.nutrition,'Storage Instruction':k.storage,'Shelf Life':k.shelf,'Manufacturer / Marketer':k.manufacturer};
function fill(el,o){Object.entries(o).filter(([,v])=>v).forEach(([a,b])=>el.insertAdjacentHTML('beforeend','<dt>'+a+'</dt><dd>'+b+'</dd>'))}fill(document.querySelector('#dgHighlights'),hi);fill(document.querySelector('#dgInformation'),info);
if(!document.querySelector('#dgInformation').children.length)document.querySelector('#dgInformation').innerHTML='<dt>Product information</dt><dd>Verified legal, nutrition and manufacturer details can be added from Admin. No unverified details are shown.</dd>';
document.querySelector('#dgAdd').onclick=()=>{if(window.addToCart)window.addToCart(id||k.name);else location.href='products.html'};
let more=document.querySelector('#dgMore');Object.entries(known).forEach(([x,v])=>{if(v.name===k.name)return;more.insertAdjacentHTML('beforeend','<article class="dg-more-card"><a href="product-detail.html?id='+x+'"><img src="'+v.image+'"><b>'+v.name+'</b><small style="display:block">'+(v.unit||'')+'</small></a></article>')});
})();
